// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: C0.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from C0.proto</summary>
public static partial class C0Reflection {

  #region Descriptor
  /// <summary>File descriptor for C0.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static C0Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CghDMC5wcm90byIxCgpDMF9Ib3VTaGFuEhIKCmlzT3BlbkRvb3IYASABKAgS",
          "DwoHbG9ja051bRgCIAEoBSILCglDMF9EYVRpbmcicAoCQzASHAoHaG91U2hh",
          "bhgBIAEoCzILLkMwX0hvdVNoYW4SGgoGZGFUaW5nGAIgASgLMgouQzBfRGFU",
          "aW5nEhYKDmxhdmVBbnN3ZXJMaXN0GAMgAygFEhgKEGxvb2tlZEFuc3dlckxp",
          "c3QYBCADKAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::C0_HouShan), global::C0_HouShan.Parser, new[]{ "IsOpenDoor", "LockNum" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::C0_DaTing), global::C0_DaTing.Parser, null, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::C0), global::C0.Parser, new[]{ "HouShan", "DaTing", "LaveAnswerList", "LookedAnswerList" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class C0_HouShan : pb::IMessage<C0_HouShan>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<C0_HouShan> _parser = new pb::MessageParser<C0_HouShan>(() => new C0_HouShan());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<C0_HouShan> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::C0Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C0_HouShan() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C0_HouShan(C0_HouShan other) : this() {
    isOpenDoor_ = other.isOpenDoor_;
    lockNum_ = other.lockNum_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C0_HouShan Clone() {
    return new C0_HouShan(this);
  }

  /// <summary>Field number for the "isOpenDoor" field.</summary>
  public const int IsOpenDoorFieldNumber = 1;
  private bool isOpenDoor_;
  /// <summary>
  ///是否开门
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsOpenDoor {
    get { return isOpenDoor_; }
    set {
      isOpenDoor_ = value;
    }
  }

  /// <summary>Field number for the "lockNum" field.</summary>
  public const int LockNumFieldNumber = 2;
  private int lockNum_;
  /// <summary>
  ///锁密码
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LockNum {
    get { return lockNum_; }
    set {
      lockNum_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as C0_HouShan);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(C0_HouShan other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IsOpenDoor != other.IsOpenDoor) return false;
    if (LockNum != other.LockNum) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (IsOpenDoor != false) hash ^= IsOpenDoor.GetHashCode();
    if (LockNum != 0) hash ^= LockNum.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (IsOpenDoor != false) {
      output.WriteRawTag(8);
      output.WriteBool(IsOpenDoor);
    }
    if (LockNum != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(LockNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (IsOpenDoor != false) {
      output.WriteRawTag(8);
      output.WriteBool(IsOpenDoor);
    }
    if (LockNum != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(LockNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (IsOpenDoor != false) {
      size += 1 + 1;
    }
    if (LockNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LockNum);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(C0_HouShan other) {
    if (other == null) {
      return;
    }
    if (other.IsOpenDoor != false) {
      IsOpenDoor = other.IsOpenDoor;
    }
    if (other.LockNum != 0) {
      LockNum = other.LockNum;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          IsOpenDoor = input.ReadBool();
          break;
        }
        case 16: {
          LockNum = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          IsOpenDoor = input.ReadBool();
          break;
        }
        case 16: {
          LockNum = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class C0_DaTing : pb::IMessage<C0_DaTing>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<C0_DaTing> _parser = new pb::MessageParser<C0_DaTing>(() => new C0_DaTing());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<C0_DaTing> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::C0Reflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C0_DaTing() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C0_DaTing(C0_DaTing other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C0_DaTing Clone() {
    return new C0_DaTing(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as C0_DaTing);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(C0_DaTing other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(C0_DaTing other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
      }
    }
  }
  #endif

}

public sealed partial class C0 : pb::IMessage<C0>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<C0> _parser = new pb::MessageParser<C0>(() => new C0());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<C0> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::C0Reflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C0() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C0(C0 other) : this() {
    houShan_ = other.houShan_ != null ? other.houShan_.Clone() : null;
    daTing_ = other.daTing_ != null ? other.daTing_.Clone() : null;
    laveAnswerList_ = other.laveAnswerList_.Clone();
    lookedAnswerList_ = other.lookedAnswerList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C0 Clone() {
    return new C0(this);
  }

  /// <summary>Field number for the "houShan" field.</summary>
  public const int HouShanFieldNumber = 1;
  private global::C0_HouShan houShan_;
  /// <summary>
  ///后山数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C0_HouShan HouShan {
    get { return houShan_; }
    set {
      houShan_ = value;
    }
  }

  /// <summary>Field number for the "daTing" field.</summary>
  public const int DaTingFieldNumber = 2;
  private global::C0_DaTing daTing_;
  /// <summary>
  ///大厅
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C0_DaTing DaTing {
    get { return daTing_; }
    set {
      daTing_ = value;
    }
  }

  /// <summary>Field number for the "laveAnswerList" field.</summary>
  public const int LaveAnswerListFieldNumber = 3;
  private static readonly pb::FieldCodec<int> _repeated_laveAnswerList_codec
      = pb::FieldCodec.ForInt32(26);
  private readonly pbc::RepeatedField<int> laveAnswerList_ = new pbc::RepeatedField<int>();
  /// <summary>
  ///剩余答案数组
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> LaveAnswerList {
    get { return laveAnswerList_; }
  }

  /// <summary>Field number for the "lookedAnswerList" field.</summary>
  public const int LookedAnswerListFieldNumber = 4;
  private static readonly pb::FieldCodec<int> _repeated_lookedAnswerList_codec
      = pb::FieldCodec.ForInt32(34);
  private readonly pbc::RepeatedField<int> lookedAnswerList_ = new pbc::RepeatedField<int>();
  /// <summary>
  ///已经看过的答案数组
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> LookedAnswerList {
    get { return lookedAnswerList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as C0);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(C0 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(HouShan, other.HouShan)) return false;
    if (!object.Equals(DaTing, other.DaTing)) return false;
    if(!laveAnswerList_.Equals(other.laveAnswerList_)) return false;
    if(!lookedAnswerList_.Equals(other.lookedAnswerList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (houShan_ != null) hash ^= HouShan.GetHashCode();
    if (daTing_ != null) hash ^= DaTing.GetHashCode();
    hash ^= laveAnswerList_.GetHashCode();
    hash ^= lookedAnswerList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (houShan_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(HouShan);
    }
    if (daTing_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(DaTing);
    }
    laveAnswerList_.WriteTo(output, _repeated_laveAnswerList_codec);
    lookedAnswerList_.WriteTo(output, _repeated_lookedAnswerList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (houShan_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(HouShan);
    }
    if (daTing_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(DaTing);
    }
    laveAnswerList_.WriteTo(ref output, _repeated_laveAnswerList_codec);
    lookedAnswerList_.WriteTo(ref output, _repeated_lookedAnswerList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (houShan_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(HouShan);
    }
    if (daTing_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DaTing);
    }
    size += laveAnswerList_.CalculateSize(_repeated_laveAnswerList_codec);
    size += lookedAnswerList_.CalculateSize(_repeated_lookedAnswerList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(C0 other) {
    if (other == null) {
      return;
    }
    if (other.houShan_ != null) {
      if (houShan_ == null) {
        HouShan = new global::C0_HouShan();
      }
      HouShan.MergeFrom(other.HouShan);
    }
    if (other.daTing_ != null) {
      if (daTing_ == null) {
        DaTing = new global::C0_DaTing();
      }
      DaTing.MergeFrom(other.DaTing);
    }
    laveAnswerList_.Add(other.laveAnswerList_);
    lookedAnswerList_.Add(other.lookedAnswerList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (houShan_ == null) {
            HouShan = new global::C0_HouShan();
          }
          input.ReadMessage(HouShan);
          break;
        }
        case 18: {
          if (daTing_ == null) {
            DaTing = new global::C0_DaTing();
          }
          input.ReadMessage(DaTing);
          break;
        }
        case 26:
        case 24: {
          laveAnswerList_.AddEntriesFrom(input, _repeated_laveAnswerList_codec);
          break;
        }
        case 34:
        case 32: {
          lookedAnswerList_.AddEntriesFrom(input, _repeated_lookedAnswerList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (houShan_ == null) {
            HouShan = new global::C0_HouShan();
          }
          input.ReadMessage(HouShan);
          break;
        }
        case 18: {
          if (daTing_ == null) {
            DaTing = new global::C0_DaTing();
          }
          input.ReadMessage(DaTing);
          break;
        }
        case 26:
        case 24: {
          laveAnswerList_.AddEntriesFrom(ref input, _repeated_laveAnswerList_codec);
          break;
        }
        case 34:
        case 32: {
          lookedAnswerList_.AddEntriesFrom(ref input, _repeated_lookedAnswerList_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
