
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.game
{
public sealed partial class Scene : Luban.BeanBase
{
    public Scene(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["name_id"].IsString) { throw new SerializationException(); }  NameId = _buf["name_id"]; }
        { if(!_buf["scene_res"].IsString) { throw new SerializationException(); }  SceneRes = _buf["scene_res"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["video"].IsString) { throw new SerializationException(); }  Video = _buf["video"]; }
    }

    public static Scene DeserializeScene(JSONNode _buf)
    {
        return new game.Scene(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述仅查看用
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 场景名称
    /// </summary>
    public readonly string NameId;
    /// <summary>
    /// 场景名字
    /// </summary>
    public readonly string SceneRes;
    /// <summary>
    /// 场景图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 场景图标
    /// </summary>
    public readonly string Video;
   
    public const int __ID__ = -462478480;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "nameId:" + NameId + ","
        + "sceneRes:" + SceneRes + ","
        + "icon:" + Icon + ","
        + "video:" + Video + ","
        + "}";
    }
}

}

