
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public game.TbScene TbScene {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbScene = new game.TbScene(loader("game_tbscene"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbScene.ResolveRef(this);
    }
}

}
