// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Account.proto

public final class AccountOuterClass {
  private AccountOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PropItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PropItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     *数量
     * </pre>
     *
     * <code>int32 num = 2;</code>
     * @return The num.
     */
    int getNum();

    /**
     * <pre>
     *是否观看
     * </pre>
     *
     * <code>bool isWatch = 3;</code>
     * @return The isWatch.
     */
    boolean getIsWatch();
  }
  /**
   * Protobuf type {@code PropItem}
   */
  public static final class PropItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PropItem)
      PropItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PropItem.newBuilder() to construct.
    private PropItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PropItem() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PropItem();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AccountOuterClass.internal_static_PropItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AccountOuterClass.internal_static_PropItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AccountOuterClass.PropItem.class, AccountOuterClass.PropItem.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NUM_FIELD_NUMBER = 2;
    private int num_ = 0;
    /**
     * <pre>
     *数量
     * </pre>
     *
     * <code>int32 num = 2;</code>
     * @return The num.
     */
    @java.lang.Override
    public int getNum() {
      return num_;
    }

    public static final int ISWATCH_FIELD_NUMBER = 3;
    private boolean isWatch_ = false;
    /**
     * <pre>
     *是否观看
     * </pre>
     *
     * <code>bool isWatch = 3;</code>
     * @return The isWatch.
     */
    @java.lang.Override
    public boolean getIsWatch() {
      return isWatch_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (num_ != 0) {
        output.writeInt32(2, num_);
      }
      if (isWatch_ != false) {
        output.writeBool(3, isWatch_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num_);
      }
      if (isWatch_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isWatch_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AccountOuterClass.PropItem)) {
        return super.equals(obj);
      }
      AccountOuterClass.PropItem other = (AccountOuterClass.PropItem) obj;

      if (getId()
          != other.getId()) return false;
      if (getNum()
          != other.getNum()) return false;
      if (getIsWatch()
          != other.getIsWatch()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
      hash = (37 * hash) + ISWATCH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsWatch());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AccountOuterClass.PropItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AccountOuterClass.PropItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AccountOuterClass.PropItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AccountOuterClass.PropItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AccountOuterClass.PropItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AccountOuterClass.PropItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AccountOuterClass.PropItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AccountOuterClass.PropItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AccountOuterClass.PropItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AccountOuterClass.PropItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AccountOuterClass.PropItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AccountOuterClass.PropItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AccountOuterClass.PropItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PropItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PropItem)
        AccountOuterClass.PropItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AccountOuterClass.internal_static_PropItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AccountOuterClass.internal_static_PropItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AccountOuterClass.PropItem.class, AccountOuterClass.PropItem.Builder.class);
      }

      // Construct using AccountOuterClass.PropItem.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        num_ = 0;
        isWatch_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AccountOuterClass.internal_static_PropItem_descriptor;
      }

      @java.lang.Override
      public AccountOuterClass.PropItem getDefaultInstanceForType() {
        return AccountOuterClass.PropItem.getDefaultInstance();
      }

      @java.lang.Override
      public AccountOuterClass.PropItem build() {
        AccountOuterClass.PropItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AccountOuterClass.PropItem buildPartial() {
        AccountOuterClass.PropItem result = new AccountOuterClass.PropItem(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(AccountOuterClass.PropItem result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.num_ = num_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isWatch_ = isWatch_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AccountOuterClass.PropItem) {
          return mergeFrom((AccountOuterClass.PropItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AccountOuterClass.PropItem other) {
        if (other == AccountOuterClass.PropItem.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        if (other.getIsWatch() != false) {
          setIsWatch(other.getIsWatch());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                num_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                isWatch_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <pre>
       *数量
       * </pre>
       *
       * <code>int32 num = 2;</code>
       * @return The num.
       */
      @java.lang.Override
      public int getNum() {
        return num_;
      }
      /**
       * <pre>
       *数量
       * </pre>
       *
       * <code>int32 num = 2;</code>
       * @param value The num to set.
       * @return This builder for chaining.
       */
      public Builder setNum(int value) {

        num_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数量
       * </pre>
       *
       * <code>int32 num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        onChanged();
        return this;
      }

      private boolean isWatch_ ;
      /**
       * <pre>
       *是否观看
       * </pre>
       *
       * <code>bool isWatch = 3;</code>
       * @return The isWatch.
       */
      @java.lang.Override
      public boolean getIsWatch() {
        return isWatch_;
      }
      /**
       * <pre>
       *是否观看
       * </pre>
       *
       * <code>bool isWatch = 3;</code>
       * @param value The isWatch to set.
       * @return This builder for chaining.
       */
      public Builder setIsWatch(boolean value) {

        isWatch_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否观看
       * </pre>
       *
       * <code>bool isWatch = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsWatch() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isWatch_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PropItem)
    }

    // @@protoc_insertion_point(class_scope:PropItem)
    private static final AccountOuterClass.PropItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AccountOuterClass.PropItem();
    }

    public static AccountOuterClass.PropItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PropItem>
        PARSER = new com.google.protobuf.AbstractParser<PropItem>() {
      @java.lang.Override
      public PropItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PropItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PropItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AccountOuterClass.PropItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Account)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *hp数量
     * </pre>
     *
     * <code>int32 hp = 1;</code>
     * @return The hp.
     */
    int getHp();

    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    java.util.List<AccountOuterClass.PropItem> 
        getPropItemListList();
    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    AccountOuterClass.PropItem getPropItemList(int index);
    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    int getPropItemListCount();
    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    java.util.List<? extends AccountOuterClass.PropItemOrBuilder> 
        getPropItemListOrBuilderList();
    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    AccountOuterClass.PropItemOrBuilder getPropItemListOrBuilder(
        int index);

    /**
     * <pre>
     *当前章节id
     * </pre>
     *
     * <code>int32 chapterId = 3;</code>
     * @return The chapterId.
     */
    int getChapterId();
  }
  /**
   * Protobuf type {@code Account}
   */
  public static final class Account extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Account)
      AccountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Account() {
      propItemList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Account();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AccountOuterClass.internal_static_Account_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AccountOuterClass.internal_static_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AccountOuterClass.Account.class, AccountOuterClass.Account.Builder.class);
    }

    public static final int HP_FIELD_NUMBER = 1;
    private int hp_ = 0;
    /**
     * <pre>
     *hp数量
     * </pre>
     *
     * <code>int32 hp = 1;</code>
     * @return The hp.
     */
    @java.lang.Override
    public int getHp() {
      return hp_;
    }

    public static final int PROPITEMLIST_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<AccountOuterClass.PropItem> propItemList_;
    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    @java.lang.Override
    public java.util.List<AccountOuterClass.PropItem> getPropItemListList() {
      return propItemList_;
    }
    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends AccountOuterClass.PropItemOrBuilder> 
        getPropItemListOrBuilderList() {
      return propItemList_;
    }
    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    @java.lang.Override
    public int getPropItemListCount() {
      return propItemList_.size();
    }
    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    @java.lang.Override
    public AccountOuterClass.PropItem getPropItemList(int index) {
      return propItemList_.get(index);
    }
    /**
     * <pre>
     *物品列表
     * </pre>
     *
     * <code>repeated .PropItem propItemList = 2;</code>
     */
    @java.lang.Override
    public AccountOuterClass.PropItemOrBuilder getPropItemListOrBuilder(
        int index) {
      return propItemList_.get(index);
    }

    public static final int CHAPTERID_FIELD_NUMBER = 3;
    private int chapterId_ = 0;
    /**
     * <pre>
     *当前章节id
     * </pre>
     *
     * <code>int32 chapterId = 3;</code>
     * @return The chapterId.
     */
    @java.lang.Override
    public int getChapterId() {
      return chapterId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hp_ != 0) {
        output.writeInt32(1, hp_);
      }
      for (int i = 0; i < propItemList_.size(); i++) {
        output.writeMessage(2, propItemList_.get(i));
      }
      if (chapterId_ != 0) {
        output.writeInt32(3, chapterId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hp_);
      }
      for (int i = 0; i < propItemList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, propItemList_.get(i));
      }
      if (chapterId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, chapterId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AccountOuterClass.Account)) {
        return super.equals(obj);
      }
      AccountOuterClass.Account other = (AccountOuterClass.Account) obj;

      if (getHp()
          != other.getHp()) return false;
      if (!getPropItemListList()
          .equals(other.getPropItemListList())) return false;
      if (getChapterId()
          != other.getChapterId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + getHp();
      if (getPropItemListCount() > 0) {
        hash = (37 * hash) + PROPITEMLIST_FIELD_NUMBER;
        hash = (53 * hash) + getPropItemListList().hashCode();
      }
      hash = (37 * hash) + CHAPTERID_FIELD_NUMBER;
      hash = (53 * hash) + getChapterId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AccountOuterClass.Account parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AccountOuterClass.Account parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AccountOuterClass.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AccountOuterClass.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AccountOuterClass.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AccountOuterClass.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AccountOuterClass.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AccountOuterClass.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AccountOuterClass.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AccountOuterClass.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AccountOuterClass.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AccountOuterClass.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AccountOuterClass.Account prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Account)
        AccountOuterClass.AccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AccountOuterClass.internal_static_Account_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AccountOuterClass.internal_static_Account_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AccountOuterClass.Account.class, AccountOuterClass.Account.Builder.class);
      }

      // Construct using AccountOuterClass.Account.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        hp_ = 0;
        if (propItemListBuilder_ == null) {
          propItemList_ = java.util.Collections.emptyList();
        } else {
          propItemList_ = null;
          propItemListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        chapterId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AccountOuterClass.internal_static_Account_descriptor;
      }

      @java.lang.Override
      public AccountOuterClass.Account getDefaultInstanceForType() {
        return AccountOuterClass.Account.getDefaultInstance();
      }

      @java.lang.Override
      public AccountOuterClass.Account build() {
        AccountOuterClass.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AccountOuterClass.Account buildPartial() {
        AccountOuterClass.Account result = new AccountOuterClass.Account(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(AccountOuterClass.Account result) {
        if (propItemListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            propItemList_ = java.util.Collections.unmodifiableList(propItemList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.propItemList_ = propItemList_;
        } else {
          result.propItemList_ = propItemListBuilder_.build();
        }
      }

      private void buildPartial0(AccountOuterClass.Account result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.hp_ = hp_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.chapterId_ = chapterId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AccountOuterClass.Account) {
          return mergeFrom((AccountOuterClass.Account)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AccountOuterClass.Account other) {
        if (other == AccountOuterClass.Account.getDefaultInstance()) return this;
        if (other.getHp() != 0) {
          setHp(other.getHp());
        }
        if (propItemListBuilder_ == null) {
          if (!other.propItemList_.isEmpty()) {
            if (propItemList_.isEmpty()) {
              propItemList_ = other.propItemList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePropItemListIsMutable();
              propItemList_.addAll(other.propItemList_);
            }
            onChanged();
          }
        } else {
          if (!other.propItemList_.isEmpty()) {
            if (propItemListBuilder_.isEmpty()) {
              propItemListBuilder_.dispose();
              propItemListBuilder_ = null;
              propItemList_ = other.propItemList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              propItemListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPropItemListFieldBuilder() : null;
            } else {
              propItemListBuilder_.addAllMessages(other.propItemList_);
            }
          }
        }
        if (other.getChapterId() != 0) {
          setChapterId(other.getChapterId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                hp_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                AccountOuterClass.PropItem m =
                    input.readMessage(
                        AccountOuterClass.PropItem.parser(),
                        extensionRegistry);
                if (propItemListBuilder_ == null) {
                  ensurePropItemListIsMutable();
                  propItemList_.add(m);
                } else {
                  propItemListBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 24: {
                chapterId_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int hp_ ;
      /**
       * <pre>
       *hp数量
       * </pre>
       *
       * <code>int32 hp = 1;</code>
       * @return The hp.
       */
      @java.lang.Override
      public int getHp() {
        return hp_;
      }
      /**
       * <pre>
       *hp数量
       * </pre>
       *
       * <code>int32 hp = 1;</code>
       * @param value The hp to set.
       * @return This builder for chaining.
       */
      public Builder setHp(int value) {

        hp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *hp数量
       * </pre>
       *
       * <code>int32 hp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hp_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<AccountOuterClass.PropItem> propItemList_ =
        java.util.Collections.emptyList();
      private void ensurePropItemListIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          propItemList_ = new java.util.ArrayList<AccountOuterClass.PropItem>(propItemList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AccountOuterClass.PropItem, AccountOuterClass.PropItem.Builder, AccountOuterClass.PropItemOrBuilder> propItemListBuilder_;

      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public java.util.List<AccountOuterClass.PropItem> getPropItemListList() {
        if (propItemListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(propItemList_);
        } else {
          return propItemListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public int getPropItemListCount() {
        if (propItemListBuilder_ == null) {
          return propItemList_.size();
        } else {
          return propItemListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public AccountOuterClass.PropItem getPropItemList(int index) {
        if (propItemListBuilder_ == null) {
          return propItemList_.get(index);
        } else {
          return propItemListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public Builder setPropItemList(
          int index, AccountOuterClass.PropItem value) {
        if (propItemListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropItemListIsMutable();
          propItemList_.set(index, value);
          onChanged();
        } else {
          propItemListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public Builder setPropItemList(
          int index, AccountOuterClass.PropItem.Builder builderForValue) {
        if (propItemListBuilder_ == null) {
          ensurePropItemListIsMutable();
          propItemList_.set(index, builderForValue.build());
          onChanged();
        } else {
          propItemListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public Builder addPropItemList(AccountOuterClass.PropItem value) {
        if (propItemListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropItemListIsMutable();
          propItemList_.add(value);
          onChanged();
        } else {
          propItemListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public Builder addPropItemList(
          int index, AccountOuterClass.PropItem value) {
        if (propItemListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropItemListIsMutable();
          propItemList_.add(index, value);
          onChanged();
        } else {
          propItemListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public Builder addPropItemList(
          AccountOuterClass.PropItem.Builder builderForValue) {
        if (propItemListBuilder_ == null) {
          ensurePropItemListIsMutable();
          propItemList_.add(builderForValue.build());
          onChanged();
        } else {
          propItemListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public Builder addPropItemList(
          int index, AccountOuterClass.PropItem.Builder builderForValue) {
        if (propItemListBuilder_ == null) {
          ensurePropItemListIsMutable();
          propItemList_.add(index, builderForValue.build());
          onChanged();
        } else {
          propItemListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public Builder addAllPropItemList(
          java.lang.Iterable<? extends AccountOuterClass.PropItem> values) {
        if (propItemListBuilder_ == null) {
          ensurePropItemListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, propItemList_);
          onChanged();
        } else {
          propItemListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public Builder clearPropItemList() {
        if (propItemListBuilder_ == null) {
          propItemList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          propItemListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public Builder removePropItemList(int index) {
        if (propItemListBuilder_ == null) {
          ensurePropItemListIsMutable();
          propItemList_.remove(index);
          onChanged();
        } else {
          propItemListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public AccountOuterClass.PropItem.Builder getPropItemListBuilder(
          int index) {
        return getPropItemListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public AccountOuterClass.PropItemOrBuilder getPropItemListOrBuilder(
          int index) {
        if (propItemListBuilder_ == null) {
          return propItemList_.get(index);  } else {
          return propItemListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public java.util.List<? extends AccountOuterClass.PropItemOrBuilder> 
           getPropItemListOrBuilderList() {
        if (propItemListBuilder_ != null) {
          return propItemListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(propItemList_);
        }
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public AccountOuterClass.PropItem.Builder addPropItemListBuilder() {
        return getPropItemListFieldBuilder().addBuilder(
            AccountOuterClass.PropItem.getDefaultInstance());
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public AccountOuterClass.PropItem.Builder addPropItemListBuilder(
          int index) {
        return getPropItemListFieldBuilder().addBuilder(
            index, AccountOuterClass.PropItem.getDefaultInstance());
      }
      /**
       * <pre>
       *物品列表
       * </pre>
       *
       * <code>repeated .PropItem propItemList = 2;</code>
       */
      public java.util.List<AccountOuterClass.PropItem.Builder> 
           getPropItemListBuilderList() {
        return getPropItemListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AccountOuterClass.PropItem, AccountOuterClass.PropItem.Builder, AccountOuterClass.PropItemOrBuilder> 
          getPropItemListFieldBuilder() {
        if (propItemListBuilder_ == null) {
          propItemListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AccountOuterClass.PropItem, AccountOuterClass.PropItem.Builder, AccountOuterClass.PropItemOrBuilder>(
                  propItemList_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          propItemList_ = null;
        }
        return propItemListBuilder_;
      }

      private int chapterId_ ;
      /**
       * <pre>
       *当前章节id
       * </pre>
       *
       * <code>int32 chapterId = 3;</code>
       * @return The chapterId.
       */
      @java.lang.Override
      public int getChapterId() {
        return chapterId_;
      }
      /**
       * <pre>
       *当前章节id
       * </pre>
       *
       * <code>int32 chapterId = 3;</code>
       * @param value The chapterId to set.
       * @return This builder for chaining.
       */
      public Builder setChapterId(int value) {

        chapterId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前章节id
       * </pre>
       *
       * <code>int32 chapterId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChapterId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chapterId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Account)
    }

    // @@protoc_insertion_point(class_scope:Account)
    private static final AccountOuterClass.Account DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AccountOuterClass.Account();
    }

    public static AccountOuterClass.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Account>
        PARSER = new com.google.protobuf.AbstractParser<Account>() {
      @java.lang.Override
      public Account parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Account> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AccountOuterClass.Account getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PropItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PropItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Account_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Account_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rAccount.proto\"4\n\010PropItem\022\n\n\002id\030\001 \001(\005\022" +
      "\013\n\003num\030\002 \001(\005\022\017\n\007isWatch\030\003 \001(\010\"I\n\007Account" +
      "\022\n\n\002hp\030\001 \001(\005\022\037\n\014propItemList\030\002 \003(\0132\t.Pro" +
      "pItem\022\021\n\tchapterId\030\003 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PropItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PropItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PropItem_descriptor,
        new java.lang.String[] { "Id", "Num", "IsWatch", });
    internal_static_Account_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Account_descriptor,
        new java.lang.String[] { "Hp", "PropItemList", "ChapterId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
