// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C0.proto

public final class C0OuterClass {
  private C0OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C0_HouShanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C0_HouShan)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否开门
     * </pre>
     *
     * <code>bool isOpenDoor = 1;</code>
     * @return The isOpenDoor.
     */
    boolean getIsOpenDoor();

    /**
     * <pre>
     *锁密码
     * </pre>
     *
     * <code>int32 lockNum = 2;</code>
     * @return The lockNum.
     */
    int getLockNum();
  }
  /**
   * Protobuf type {@code C0_HouShan}
   */
  public static final class C0_HouShan extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C0_HouShan)
      C0_HouShanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C0_HouShan.newBuilder() to construct.
    private C0_HouShan(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C0_HouShan() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C0_HouShan();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return C0OuterClass.internal_static_C0_HouShan_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return C0OuterClass.internal_static_C0_HouShan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              C0OuterClass.C0_HouShan.class, C0OuterClass.C0_HouShan.Builder.class);
    }

    public static final int ISOPENDOOR_FIELD_NUMBER = 1;
    private boolean isOpenDoor_ = false;
    /**
     * <pre>
     *是否开门
     * </pre>
     *
     * <code>bool isOpenDoor = 1;</code>
     * @return The isOpenDoor.
     */
    @java.lang.Override
    public boolean getIsOpenDoor() {
      return isOpenDoor_;
    }

    public static final int LOCKNUM_FIELD_NUMBER = 2;
    private int lockNum_ = 0;
    /**
     * <pre>
     *锁密码
     * </pre>
     *
     * <code>int32 lockNum = 2;</code>
     * @return The lockNum.
     */
    @java.lang.Override
    public int getLockNum() {
      return lockNum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isOpenDoor_ != false) {
        output.writeBool(1, isOpenDoor_);
      }
      if (lockNum_ != 0) {
        output.writeInt32(2, lockNum_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isOpenDoor_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isOpenDoor_);
      }
      if (lockNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lockNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof C0OuterClass.C0_HouShan)) {
        return super.equals(obj);
      }
      C0OuterClass.C0_HouShan other = (C0OuterClass.C0_HouShan) obj;

      if (getIsOpenDoor()
          != other.getIsOpenDoor()) return false;
      if (getLockNum()
          != other.getLockNum()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISOPENDOOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOpenDoor());
      hash = (37 * hash) + LOCKNUM_FIELD_NUMBER;
      hash = (53 * hash) + getLockNum();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static C0OuterClass.C0_HouShan parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C0OuterClass.C0_HouShan parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C0OuterClass.C0_HouShan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C0OuterClass.C0_HouShan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C0OuterClass.C0_HouShan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C0OuterClass.C0_HouShan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C0OuterClass.C0_HouShan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static C0OuterClass.C0_HouShan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static C0OuterClass.C0_HouShan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static C0OuterClass.C0_HouShan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static C0OuterClass.C0_HouShan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static C0OuterClass.C0_HouShan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(C0OuterClass.C0_HouShan prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C0_HouShan}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C0_HouShan)
        C0OuterClass.C0_HouShanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return C0OuterClass.internal_static_C0_HouShan_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return C0OuterClass.internal_static_C0_HouShan_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                C0OuterClass.C0_HouShan.class, C0OuterClass.C0_HouShan.Builder.class);
      }

      // Construct using C0OuterClass.C0_HouShan.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        isOpenDoor_ = false;
        lockNum_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return C0OuterClass.internal_static_C0_HouShan_descriptor;
      }

      @java.lang.Override
      public C0OuterClass.C0_HouShan getDefaultInstanceForType() {
        return C0OuterClass.C0_HouShan.getDefaultInstance();
      }

      @java.lang.Override
      public C0OuterClass.C0_HouShan build() {
        C0OuterClass.C0_HouShan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public C0OuterClass.C0_HouShan buildPartial() {
        C0OuterClass.C0_HouShan result = new C0OuterClass.C0_HouShan(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(C0OuterClass.C0_HouShan result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isOpenDoor_ = isOpenDoor_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.lockNum_ = lockNum_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof C0OuterClass.C0_HouShan) {
          return mergeFrom((C0OuterClass.C0_HouShan)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(C0OuterClass.C0_HouShan other) {
        if (other == C0OuterClass.C0_HouShan.getDefaultInstance()) return this;
        if (other.getIsOpenDoor() != false) {
          setIsOpenDoor(other.getIsOpenDoor());
        }
        if (other.getLockNum() != 0) {
          setLockNum(other.getLockNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                isOpenDoor_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                lockNum_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean isOpenDoor_ ;
      /**
       * <pre>
       *是否开门
       * </pre>
       *
       * <code>bool isOpenDoor = 1;</code>
       * @return The isOpenDoor.
       */
      @java.lang.Override
      public boolean getIsOpenDoor() {
        return isOpenDoor_;
      }
      /**
       * <pre>
       *是否开门
       * </pre>
       *
       * <code>bool isOpenDoor = 1;</code>
       * @param value The isOpenDoor to set.
       * @return This builder for chaining.
       */
      public Builder setIsOpenDoor(boolean value) {

        isOpenDoor_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否开门
       * </pre>
       *
       * <code>bool isOpenDoor = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOpenDoor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isOpenDoor_ = false;
        onChanged();
        return this;
      }

      private int lockNum_ ;
      /**
       * <pre>
       *锁密码
       * </pre>
       *
       * <code>int32 lockNum = 2;</code>
       * @return The lockNum.
       */
      @java.lang.Override
      public int getLockNum() {
        return lockNum_;
      }
      /**
       * <pre>
       *锁密码
       * </pre>
       *
       * <code>int32 lockNum = 2;</code>
       * @param value The lockNum to set.
       * @return This builder for chaining.
       */
      public Builder setLockNum(int value) {

        lockNum_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *锁密码
       * </pre>
       *
       * <code>int32 lockNum = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLockNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lockNum_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C0_HouShan)
    }

    // @@protoc_insertion_point(class_scope:C0_HouShan)
    private static final C0OuterClass.C0_HouShan DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new C0OuterClass.C0_HouShan();
    }

    public static C0OuterClass.C0_HouShan getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C0_HouShan>
        PARSER = new com.google.protobuf.AbstractParser<C0_HouShan>() {
      @java.lang.Override
      public C0_HouShan parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<C0_HouShan> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C0_HouShan> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public C0OuterClass.C0_HouShan getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C0_DaTingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C0_DaTing)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code C0_DaTing}
   */
  public static final class C0_DaTing extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C0_DaTing)
      C0_DaTingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C0_DaTing.newBuilder() to construct.
    private C0_DaTing(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C0_DaTing() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C0_DaTing();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return C0OuterClass.internal_static_C0_DaTing_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return C0OuterClass.internal_static_C0_DaTing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              C0OuterClass.C0_DaTing.class, C0OuterClass.C0_DaTing.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof C0OuterClass.C0_DaTing)) {
        return super.equals(obj);
      }
      C0OuterClass.C0_DaTing other = (C0OuterClass.C0_DaTing) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static C0OuterClass.C0_DaTing parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C0OuterClass.C0_DaTing parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C0OuterClass.C0_DaTing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C0OuterClass.C0_DaTing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C0OuterClass.C0_DaTing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C0OuterClass.C0_DaTing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C0OuterClass.C0_DaTing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static C0OuterClass.C0_DaTing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static C0OuterClass.C0_DaTing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static C0OuterClass.C0_DaTing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static C0OuterClass.C0_DaTing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static C0OuterClass.C0_DaTing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(C0OuterClass.C0_DaTing prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C0_DaTing}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C0_DaTing)
        C0OuterClass.C0_DaTingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return C0OuterClass.internal_static_C0_DaTing_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return C0OuterClass.internal_static_C0_DaTing_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                C0OuterClass.C0_DaTing.class, C0OuterClass.C0_DaTing.Builder.class);
      }

      // Construct using C0OuterClass.C0_DaTing.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return C0OuterClass.internal_static_C0_DaTing_descriptor;
      }

      @java.lang.Override
      public C0OuterClass.C0_DaTing getDefaultInstanceForType() {
        return C0OuterClass.C0_DaTing.getDefaultInstance();
      }

      @java.lang.Override
      public C0OuterClass.C0_DaTing build() {
        C0OuterClass.C0_DaTing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public C0OuterClass.C0_DaTing buildPartial() {
        C0OuterClass.C0_DaTing result = new C0OuterClass.C0_DaTing(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof C0OuterClass.C0_DaTing) {
          return mergeFrom((C0OuterClass.C0_DaTing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(C0OuterClass.C0_DaTing other) {
        if (other == C0OuterClass.C0_DaTing.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C0_DaTing)
    }

    // @@protoc_insertion_point(class_scope:C0_DaTing)
    private static final C0OuterClass.C0_DaTing DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new C0OuterClass.C0_DaTing();
    }

    public static C0OuterClass.C0_DaTing getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C0_DaTing>
        PARSER = new com.google.protobuf.AbstractParser<C0_DaTing>() {
      @java.lang.Override
      public C0_DaTing parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<C0_DaTing> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C0_DaTing> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public C0OuterClass.C0_DaTing getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C0OrBuilder extends
      // @@protoc_insertion_point(interface_extends:C0)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *后山数据
     * </pre>
     *
     * <code>.C0_HouShan houShan = 1;</code>
     * @return Whether the houShan field is set.
     */
    boolean hasHouShan();
    /**
     * <pre>
     *后山数据
     * </pre>
     *
     * <code>.C0_HouShan houShan = 1;</code>
     * @return The houShan.
     */
    C0OuterClass.C0_HouShan getHouShan();
    /**
     * <pre>
     *后山数据
     * </pre>
     *
     * <code>.C0_HouShan houShan = 1;</code>
     */
    C0OuterClass.C0_HouShanOrBuilder getHouShanOrBuilder();

    /**
     * <pre>
     *大厅
     * </pre>
     *
     * <code>.C0_DaTing daTing = 2;</code>
     * @return Whether the daTing field is set.
     */
    boolean hasDaTing();
    /**
     * <pre>
     *大厅
     * </pre>
     *
     * <code>.C0_DaTing daTing = 2;</code>
     * @return The daTing.
     */
    C0OuterClass.C0_DaTing getDaTing();
    /**
     * <pre>
     *大厅
     * </pre>
     *
     * <code>.C0_DaTing daTing = 2;</code>
     */
    C0OuterClass.C0_DaTingOrBuilder getDaTingOrBuilder();

    /**
     * <pre>
     *剩余答案数组
     * </pre>
     *
     * <code>repeated int32 laveAnswerList = 3;</code>
     * @return A list containing the laveAnswerList.
     */
    java.util.List<java.lang.Integer> getLaveAnswerListList();
    /**
     * <pre>
     *剩余答案数组
     * </pre>
     *
     * <code>repeated int32 laveAnswerList = 3;</code>
     * @return The count of laveAnswerList.
     */
    int getLaveAnswerListCount();
    /**
     * <pre>
     *剩余答案数组
     * </pre>
     *
     * <code>repeated int32 laveAnswerList = 3;</code>
     * @param index The index of the element to return.
     * @return The laveAnswerList at the given index.
     */
    int getLaveAnswerList(int index);

    /**
     * <pre>
     *已经看过的答案数组
     * </pre>
     *
     * <code>repeated int32 lookedAnswerList = 4;</code>
     * @return A list containing the lookedAnswerList.
     */
    java.util.List<java.lang.Integer> getLookedAnswerListList();
    /**
     * <pre>
     *已经看过的答案数组
     * </pre>
     *
     * <code>repeated int32 lookedAnswerList = 4;</code>
     * @return The count of lookedAnswerList.
     */
    int getLookedAnswerListCount();
    /**
     * <pre>
     *已经看过的答案数组
     * </pre>
     *
     * <code>repeated int32 lookedAnswerList = 4;</code>
     * @param index The index of the element to return.
     * @return The lookedAnswerList at the given index.
     */
    int getLookedAnswerList(int index);
  }
  /**
   * Protobuf type {@code C0}
   */
  public static final class C0 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C0)
      C0OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C0.newBuilder() to construct.
    private C0(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C0() {
      laveAnswerList_ = emptyIntList();
      lookedAnswerList_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C0();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return C0OuterClass.internal_static_C0_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return C0OuterClass.internal_static_C0_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              C0OuterClass.C0.class, C0OuterClass.C0.Builder.class);
    }

    public static final int HOUSHAN_FIELD_NUMBER = 1;
    private C0OuterClass.C0_HouShan houShan_;
    /**
     * <pre>
     *后山数据
     * </pre>
     *
     * <code>.C0_HouShan houShan = 1;</code>
     * @return Whether the houShan field is set.
     */
    @java.lang.Override
    public boolean hasHouShan() {
      return houShan_ != null;
    }
    /**
     * <pre>
     *后山数据
     * </pre>
     *
     * <code>.C0_HouShan houShan = 1;</code>
     * @return The houShan.
     */
    @java.lang.Override
    public C0OuterClass.C0_HouShan getHouShan() {
      return houShan_ == null ? C0OuterClass.C0_HouShan.getDefaultInstance() : houShan_;
    }
    /**
     * <pre>
     *后山数据
     * </pre>
     *
     * <code>.C0_HouShan houShan = 1;</code>
     */
    @java.lang.Override
    public C0OuterClass.C0_HouShanOrBuilder getHouShanOrBuilder() {
      return houShan_ == null ? C0OuterClass.C0_HouShan.getDefaultInstance() : houShan_;
    }

    public static final int DATING_FIELD_NUMBER = 2;
    private C0OuterClass.C0_DaTing daTing_;
    /**
     * <pre>
     *大厅
     * </pre>
     *
     * <code>.C0_DaTing daTing = 2;</code>
     * @return Whether the daTing field is set.
     */
    @java.lang.Override
    public boolean hasDaTing() {
      return daTing_ != null;
    }
    /**
     * <pre>
     *大厅
     * </pre>
     *
     * <code>.C0_DaTing daTing = 2;</code>
     * @return The daTing.
     */
    @java.lang.Override
    public C0OuterClass.C0_DaTing getDaTing() {
      return daTing_ == null ? C0OuterClass.C0_DaTing.getDefaultInstance() : daTing_;
    }
    /**
     * <pre>
     *大厅
     * </pre>
     *
     * <code>.C0_DaTing daTing = 2;</code>
     */
    @java.lang.Override
    public C0OuterClass.C0_DaTingOrBuilder getDaTingOrBuilder() {
      return daTing_ == null ? C0OuterClass.C0_DaTing.getDefaultInstance() : daTing_;
    }

    public static final int LAVEANSWERLIST_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList laveAnswerList_;
    /**
     * <pre>
     *剩余答案数组
     * </pre>
     *
     * <code>repeated int32 laveAnswerList = 3;</code>
     * @return A list containing the laveAnswerList.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getLaveAnswerListList() {
      return laveAnswerList_;
    }
    /**
     * <pre>
     *剩余答案数组
     * </pre>
     *
     * <code>repeated int32 laveAnswerList = 3;</code>
     * @return The count of laveAnswerList.
     */
    public int getLaveAnswerListCount() {
      return laveAnswerList_.size();
    }
    /**
     * <pre>
     *剩余答案数组
     * </pre>
     *
     * <code>repeated int32 laveAnswerList = 3;</code>
     * @param index The index of the element to return.
     * @return The laveAnswerList at the given index.
     */
    public int getLaveAnswerList(int index) {
      return laveAnswerList_.getInt(index);
    }
    private int laveAnswerListMemoizedSerializedSize = -1;

    public static final int LOOKEDANSWERLIST_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList lookedAnswerList_;
    /**
     * <pre>
     *已经看过的答案数组
     * </pre>
     *
     * <code>repeated int32 lookedAnswerList = 4;</code>
     * @return A list containing the lookedAnswerList.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getLookedAnswerListList() {
      return lookedAnswerList_;
    }
    /**
     * <pre>
     *已经看过的答案数组
     * </pre>
     *
     * <code>repeated int32 lookedAnswerList = 4;</code>
     * @return The count of lookedAnswerList.
     */
    public int getLookedAnswerListCount() {
      return lookedAnswerList_.size();
    }
    /**
     * <pre>
     *已经看过的答案数组
     * </pre>
     *
     * <code>repeated int32 lookedAnswerList = 4;</code>
     * @param index The index of the element to return.
     * @return The lookedAnswerList at the given index.
     */
    public int getLookedAnswerList(int index) {
      return lookedAnswerList_.getInt(index);
    }
    private int lookedAnswerListMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (houShan_ != null) {
        output.writeMessage(1, getHouShan());
      }
      if (daTing_ != null) {
        output.writeMessage(2, getDaTing());
      }
      if (getLaveAnswerListList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(laveAnswerListMemoizedSerializedSize);
      }
      for (int i = 0; i < laveAnswerList_.size(); i++) {
        output.writeInt32NoTag(laveAnswerList_.getInt(i));
      }
      if (getLookedAnswerListList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(lookedAnswerListMemoizedSerializedSize);
      }
      for (int i = 0; i < lookedAnswerList_.size(); i++) {
        output.writeInt32NoTag(lookedAnswerList_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (houShan_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHouShan());
      }
      if (daTing_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDaTing());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < laveAnswerList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(laveAnswerList_.getInt(i));
        }
        size += dataSize;
        if (!getLaveAnswerListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        laveAnswerListMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < lookedAnswerList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(lookedAnswerList_.getInt(i));
        }
        size += dataSize;
        if (!getLookedAnswerListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        lookedAnswerListMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof C0OuterClass.C0)) {
        return super.equals(obj);
      }
      C0OuterClass.C0 other = (C0OuterClass.C0) obj;

      if (hasHouShan() != other.hasHouShan()) return false;
      if (hasHouShan()) {
        if (!getHouShan()
            .equals(other.getHouShan())) return false;
      }
      if (hasDaTing() != other.hasDaTing()) return false;
      if (hasDaTing()) {
        if (!getDaTing()
            .equals(other.getDaTing())) return false;
      }
      if (!getLaveAnswerListList()
          .equals(other.getLaveAnswerListList())) return false;
      if (!getLookedAnswerListList()
          .equals(other.getLookedAnswerListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHouShan()) {
        hash = (37 * hash) + HOUSHAN_FIELD_NUMBER;
        hash = (53 * hash) + getHouShan().hashCode();
      }
      if (hasDaTing()) {
        hash = (37 * hash) + DATING_FIELD_NUMBER;
        hash = (53 * hash) + getDaTing().hashCode();
      }
      if (getLaveAnswerListCount() > 0) {
        hash = (37 * hash) + LAVEANSWERLIST_FIELD_NUMBER;
        hash = (53 * hash) + getLaveAnswerListList().hashCode();
      }
      if (getLookedAnswerListCount() > 0) {
        hash = (37 * hash) + LOOKEDANSWERLIST_FIELD_NUMBER;
        hash = (53 * hash) + getLookedAnswerListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static C0OuterClass.C0 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C0OuterClass.C0 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C0OuterClass.C0 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C0OuterClass.C0 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C0OuterClass.C0 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C0OuterClass.C0 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C0OuterClass.C0 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static C0OuterClass.C0 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static C0OuterClass.C0 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static C0OuterClass.C0 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static C0OuterClass.C0 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static C0OuterClass.C0 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(C0OuterClass.C0 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C0}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C0)
        C0OuterClass.C0OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return C0OuterClass.internal_static_C0_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return C0OuterClass.internal_static_C0_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                C0OuterClass.C0.class, C0OuterClass.C0.Builder.class);
      }

      // Construct using C0OuterClass.C0.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        houShan_ = null;
        if (houShanBuilder_ != null) {
          houShanBuilder_.dispose();
          houShanBuilder_ = null;
        }
        daTing_ = null;
        if (daTingBuilder_ != null) {
          daTingBuilder_.dispose();
          daTingBuilder_ = null;
        }
        laveAnswerList_ = emptyIntList();
        lookedAnswerList_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return C0OuterClass.internal_static_C0_descriptor;
      }

      @java.lang.Override
      public C0OuterClass.C0 getDefaultInstanceForType() {
        return C0OuterClass.C0.getDefaultInstance();
      }

      @java.lang.Override
      public C0OuterClass.C0 build() {
        C0OuterClass.C0 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public C0OuterClass.C0 buildPartial() {
        C0OuterClass.C0 result = new C0OuterClass.C0(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(C0OuterClass.C0 result) {
        if (((bitField0_ & 0x00000004) != 0)) {
          laveAnswerList_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.laveAnswerList_ = laveAnswerList_;
        if (((bitField0_ & 0x00000008) != 0)) {
          lookedAnswerList_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.lookedAnswerList_ = lookedAnswerList_;
      }

      private void buildPartial0(C0OuterClass.C0 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.houShan_ = houShanBuilder_ == null
              ? houShan_
              : houShanBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.daTing_ = daTingBuilder_ == null
              ? daTing_
              : daTingBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof C0OuterClass.C0) {
          return mergeFrom((C0OuterClass.C0)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(C0OuterClass.C0 other) {
        if (other == C0OuterClass.C0.getDefaultInstance()) return this;
        if (other.hasHouShan()) {
          mergeHouShan(other.getHouShan());
        }
        if (other.hasDaTing()) {
          mergeDaTing(other.getDaTing());
        }
        if (!other.laveAnswerList_.isEmpty()) {
          if (laveAnswerList_.isEmpty()) {
            laveAnswerList_ = other.laveAnswerList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureLaveAnswerListIsMutable();
            laveAnswerList_.addAll(other.laveAnswerList_);
          }
          onChanged();
        }
        if (!other.lookedAnswerList_.isEmpty()) {
          if (lookedAnswerList_.isEmpty()) {
            lookedAnswerList_ = other.lookedAnswerList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLookedAnswerListIsMutable();
            lookedAnswerList_.addAll(other.lookedAnswerList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHouShanFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getDaTingFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                int v = input.readInt32();
                ensureLaveAnswerListIsMutable();
                laveAnswerList_.addInt(v);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureLaveAnswerListIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  laveAnswerList_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 32: {
                int v = input.readInt32();
                ensureLookedAnswerListIsMutable();
                lookedAnswerList_.addInt(v);
                break;
              } // case 32
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureLookedAnswerListIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  lookedAnswerList_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private C0OuterClass.C0_HouShan houShan_;
      private com.google.protobuf.SingleFieldBuilderV3<
          C0OuterClass.C0_HouShan, C0OuterClass.C0_HouShan.Builder, C0OuterClass.C0_HouShanOrBuilder> houShanBuilder_;
      /**
       * <pre>
       *后山数据
       * </pre>
       *
       * <code>.C0_HouShan houShan = 1;</code>
       * @return Whether the houShan field is set.
       */
      public boolean hasHouShan() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *后山数据
       * </pre>
       *
       * <code>.C0_HouShan houShan = 1;</code>
       * @return The houShan.
       */
      public C0OuterClass.C0_HouShan getHouShan() {
        if (houShanBuilder_ == null) {
          return houShan_ == null ? C0OuterClass.C0_HouShan.getDefaultInstance() : houShan_;
        } else {
          return houShanBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *后山数据
       * </pre>
       *
       * <code>.C0_HouShan houShan = 1;</code>
       */
      public Builder setHouShan(C0OuterClass.C0_HouShan value) {
        if (houShanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          houShan_ = value;
        } else {
          houShanBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *后山数据
       * </pre>
       *
       * <code>.C0_HouShan houShan = 1;</code>
       */
      public Builder setHouShan(
          C0OuterClass.C0_HouShan.Builder builderForValue) {
        if (houShanBuilder_ == null) {
          houShan_ = builderForValue.build();
        } else {
          houShanBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *后山数据
       * </pre>
       *
       * <code>.C0_HouShan houShan = 1;</code>
       */
      public Builder mergeHouShan(C0OuterClass.C0_HouShan value) {
        if (houShanBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            houShan_ != null &&
            houShan_ != C0OuterClass.C0_HouShan.getDefaultInstance()) {
            getHouShanBuilder().mergeFrom(value);
          } else {
            houShan_ = value;
          }
        } else {
          houShanBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *后山数据
       * </pre>
       *
       * <code>.C0_HouShan houShan = 1;</code>
       */
      public Builder clearHouShan() {
        bitField0_ = (bitField0_ & ~0x00000001);
        houShan_ = null;
        if (houShanBuilder_ != null) {
          houShanBuilder_.dispose();
          houShanBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       *后山数据
       * </pre>
       *
       * <code>.C0_HouShan houShan = 1;</code>
       */
      public C0OuterClass.C0_HouShan.Builder getHouShanBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHouShanFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *后山数据
       * </pre>
       *
       * <code>.C0_HouShan houShan = 1;</code>
       */
      public C0OuterClass.C0_HouShanOrBuilder getHouShanOrBuilder() {
        if (houShanBuilder_ != null) {
          return houShanBuilder_.getMessageOrBuilder();
        } else {
          return houShan_ == null ?
              C0OuterClass.C0_HouShan.getDefaultInstance() : houShan_;
        }
      }
      /**
       * <pre>
       *后山数据
       * </pre>
       *
       * <code>.C0_HouShan houShan = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          C0OuterClass.C0_HouShan, C0OuterClass.C0_HouShan.Builder, C0OuterClass.C0_HouShanOrBuilder> 
          getHouShanFieldBuilder() {
        if (houShanBuilder_ == null) {
          houShanBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              C0OuterClass.C0_HouShan, C0OuterClass.C0_HouShan.Builder, C0OuterClass.C0_HouShanOrBuilder>(
                  getHouShan(),
                  getParentForChildren(),
                  isClean());
          houShan_ = null;
        }
        return houShanBuilder_;
      }

      private C0OuterClass.C0_DaTing daTing_;
      private com.google.protobuf.SingleFieldBuilderV3<
          C0OuterClass.C0_DaTing, C0OuterClass.C0_DaTing.Builder, C0OuterClass.C0_DaTingOrBuilder> daTingBuilder_;
      /**
       * <pre>
       *大厅
       * </pre>
       *
       * <code>.C0_DaTing daTing = 2;</code>
       * @return Whether the daTing field is set.
       */
      public boolean hasDaTing() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *大厅
       * </pre>
       *
       * <code>.C0_DaTing daTing = 2;</code>
       * @return The daTing.
       */
      public C0OuterClass.C0_DaTing getDaTing() {
        if (daTingBuilder_ == null) {
          return daTing_ == null ? C0OuterClass.C0_DaTing.getDefaultInstance() : daTing_;
        } else {
          return daTingBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *大厅
       * </pre>
       *
       * <code>.C0_DaTing daTing = 2;</code>
       */
      public Builder setDaTing(C0OuterClass.C0_DaTing value) {
        if (daTingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          daTing_ = value;
        } else {
          daTingBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *大厅
       * </pre>
       *
       * <code>.C0_DaTing daTing = 2;</code>
       */
      public Builder setDaTing(
          C0OuterClass.C0_DaTing.Builder builderForValue) {
        if (daTingBuilder_ == null) {
          daTing_ = builderForValue.build();
        } else {
          daTingBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *大厅
       * </pre>
       *
       * <code>.C0_DaTing daTing = 2;</code>
       */
      public Builder mergeDaTing(C0OuterClass.C0_DaTing value) {
        if (daTingBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            daTing_ != null &&
            daTing_ != C0OuterClass.C0_DaTing.getDefaultInstance()) {
            getDaTingBuilder().mergeFrom(value);
          } else {
            daTing_ = value;
          }
        } else {
          daTingBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *大厅
       * </pre>
       *
       * <code>.C0_DaTing daTing = 2;</code>
       */
      public Builder clearDaTing() {
        bitField0_ = (bitField0_ & ~0x00000002);
        daTing_ = null;
        if (daTingBuilder_ != null) {
          daTingBuilder_.dispose();
          daTingBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       *大厅
       * </pre>
       *
       * <code>.C0_DaTing daTing = 2;</code>
       */
      public C0OuterClass.C0_DaTing.Builder getDaTingBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDaTingFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *大厅
       * </pre>
       *
       * <code>.C0_DaTing daTing = 2;</code>
       */
      public C0OuterClass.C0_DaTingOrBuilder getDaTingOrBuilder() {
        if (daTingBuilder_ != null) {
          return daTingBuilder_.getMessageOrBuilder();
        } else {
          return daTing_ == null ?
              C0OuterClass.C0_DaTing.getDefaultInstance() : daTing_;
        }
      }
      /**
       * <pre>
       *大厅
       * </pre>
       *
       * <code>.C0_DaTing daTing = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          C0OuterClass.C0_DaTing, C0OuterClass.C0_DaTing.Builder, C0OuterClass.C0_DaTingOrBuilder> 
          getDaTingFieldBuilder() {
        if (daTingBuilder_ == null) {
          daTingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              C0OuterClass.C0_DaTing, C0OuterClass.C0_DaTing.Builder, C0OuterClass.C0_DaTingOrBuilder>(
                  getDaTing(),
                  getParentForChildren(),
                  isClean());
          daTing_ = null;
        }
        return daTingBuilder_;
      }

      private com.google.protobuf.Internal.IntList laveAnswerList_ = emptyIntList();
      private void ensureLaveAnswerListIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          laveAnswerList_ = mutableCopy(laveAnswerList_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <pre>
       *剩余答案数组
       * </pre>
       *
       * <code>repeated int32 laveAnswerList = 3;</code>
       * @return A list containing the laveAnswerList.
       */
      public java.util.List<java.lang.Integer>
          getLaveAnswerListList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(laveAnswerList_) : laveAnswerList_;
      }
      /**
       * <pre>
       *剩余答案数组
       * </pre>
       *
       * <code>repeated int32 laveAnswerList = 3;</code>
       * @return The count of laveAnswerList.
       */
      public int getLaveAnswerListCount() {
        return laveAnswerList_.size();
      }
      /**
       * <pre>
       *剩余答案数组
       * </pre>
       *
       * <code>repeated int32 laveAnswerList = 3;</code>
       * @param index The index of the element to return.
       * @return The laveAnswerList at the given index.
       */
      public int getLaveAnswerList(int index) {
        return laveAnswerList_.getInt(index);
      }
      /**
       * <pre>
       *剩余答案数组
       * </pre>
       *
       * <code>repeated int32 laveAnswerList = 3;</code>
       * @param index The index to set the value at.
       * @param value The laveAnswerList to set.
       * @return This builder for chaining.
       */
      public Builder setLaveAnswerList(
          int index, int value) {

        ensureLaveAnswerListIsMutable();
        laveAnswerList_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *剩余答案数组
       * </pre>
       *
       * <code>repeated int32 laveAnswerList = 3;</code>
       * @param value The laveAnswerList to add.
       * @return This builder for chaining.
       */
      public Builder addLaveAnswerList(int value) {

        ensureLaveAnswerListIsMutable();
        laveAnswerList_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *剩余答案数组
       * </pre>
       *
       * <code>repeated int32 laveAnswerList = 3;</code>
       * @param values The laveAnswerList to add.
       * @return This builder for chaining.
       */
      public Builder addAllLaveAnswerList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLaveAnswerListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, laveAnswerList_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *剩余答案数组
       * </pre>
       *
       * <code>repeated int32 laveAnswerList = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLaveAnswerList() {
        laveAnswerList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList lookedAnswerList_ = emptyIntList();
      private void ensureLookedAnswerListIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          lookedAnswerList_ = mutableCopy(lookedAnswerList_);
          bitField0_ |= 0x00000008;
        }
      }
      /**
       * <pre>
       *已经看过的答案数组
       * </pre>
       *
       * <code>repeated int32 lookedAnswerList = 4;</code>
       * @return A list containing the lookedAnswerList.
       */
      public java.util.List<java.lang.Integer>
          getLookedAnswerListList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(lookedAnswerList_) : lookedAnswerList_;
      }
      /**
       * <pre>
       *已经看过的答案数组
       * </pre>
       *
       * <code>repeated int32 lookedAnswerList = 4;</code>
       * @return The count of lookedAnswerList.
       */
      public int getLookedAnswerListCount() {
        return lookedAnswerList_.size();
      }
      /**
       * <pre>
       *已经看过的答案数组
       * </pre>
       *
       * <code>repeated int32 lookedAnswerList = 4;</code>
       * @param index The index of the element to return.
       * @return The lookedAnswerList at the given index.
       */
      public int getLookedAnswerList(int index) {
        return lookedAnswerList_.getInt(index);
      }
      /**
       * <pre>
       *已经看过的答案数组
       * </pre>
       *
       * <code>repeated int32 lookedAnswerList = 4;</code>
       * @param index The index to set the value at.
       * @param value The lookedAnswerList to set.
       * @return This builder for chaining.
       */
      public Builder setLookedAnswerList(
          int index, int value) {

        ensureLookedAnswerListIsMutable();
        lookedAnswerList_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已经看过的答案数组
       * </pre>
       *
       * <code>repeated int32 lookedAnswerList = 4;</code>
       * @param value The lookedAnswerList to add.
       * @return This builder for chaining.
       */
      public Builder addLookedAnswerList(int value) {

        ensureLookedAnswerListIsMutable();
        lookedAnswerList_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已经看过的答案数组
       * </pre>
       *
       * <code>repeated int32 lookedAnswerList = 4;</code>
       * @param values The lookedAnswerList to add.
       * @return This builder for chaining.
       */
      public Builder addAllLookedAnswerList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLookedAnswerListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lookedAnswerList_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已经看过的答案数组
       * </pre>
       *
       * <code>repeated int32 lookedAnswerList = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLookedAnswerList() {
        lookedAnswerList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C0)
    }

    // @@protoc_insertion_point(class_scope:C0)
    private static final C0OuterClass.C0 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new C0OuterClass.C0();
    }

    public static C0OuterClass.C0 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C0>
        PARSER = new com.google.protobuf.AbstractParser<C0>() {
      @java.lang.Override
      public C0 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<C0> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C0> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public C0OuterClass.C0 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C0_HouShan_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C0_HouShan_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C0_DaTing_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C0_DaTing_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C0_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C0_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010C0.proto\"1\n\nC0_HouShan\022\022\n\nisOpenDoor\030\001" +
      " \001(\010\022\017\n\007lockNum\030\002 \001(\005\"\013\n\tC0_DaTing\"p\n\002C0" +
      "\022\034\n\007houShan\030\001 \001(\0132\013.C0_HouShan\022\032\n\006daTing" +
      "\030\002 \001(\0132\n.C0_DaTing\022\026\n\016laveAnswerList\030\003 \003" +
      "(\005\022\030\n\020lookedAnswerList\030\004 \003(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_C0_HouShan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_C0_HouShan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C0_HouShan_descriptor,
        new java.lang.String[] { "IsOpenDoor", "LockNum", });
    internal_static_C0_DaTing_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_C0_DaTing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C0_DaTing_descriptor,
        new java.lang.String[] { });
    internal_static_C0_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_C0_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C0_descriptor,
        new java.lang.String[] { "HouShan", "DaTing", "LaveAnswerList", "LookedAnswerList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
